# Stage 1: Build the React Application
FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve with Nginx (Production Profile)
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# We inject the prod conf here instead of the default local one
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
